### PR TITLE
an imdb id can have only 6 number (eg : tt241527)

### PR DESCRIPTION
**Pull request by Nymerea**

### CODE REVIEW

**Comment by Nymerea** [comment]
Can you push this change to maven repo ( https://mvnrepository.com/artifact/org.tinymediamanager/api-scraper ) ?

**Comment by mlaggner** [comment]
thanks for this pull request!

**Comment by Nymerea** [comment]
Sorry to insist, but can you push new update to maven repo ?

**Comment by myron0815** [comment]
well... IMDB IDs are always zero padded.
Even when you point your browser to http://www.imdb.com/title/tt241527 it will redirect you to http://www.imdb.com/title/tt0241527

API is built every night;
You'll find it in our Sonatype snapshot repository.

**Comment by Nymerea** [comment]
Oh I didn't know about that. Thanks for the knowledge.

It's just I use your api in that way :

{{{
      ImdbMetadataProvider imdbProvider = new ImdbMetadataProvider();
        MediaScrapeOptions options = new MediaScrapeOptions(MediaType.MOVIE);
        options.setImdbId("tt241527");
        options.setLanguage(Locale.ENGLISH);
        MediaMetadata metadata = imdbProvider.getMetadata(options);
}}}

and the MetadataUtil say it's not a valid imdb id. Maybe we should change it for adding as much 0 as needed ?

**Comment by myron0815** [comment]
hmm.. good question.
for validation, we even would need to check for tt+anynumber
We would need to change the scraper(s), to recognise the format... but since it is always promoted on IMDB side, i would always use the 7 digits number on client side.... TBD

**Pull request merged**
